/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicial;

import dados.Paciente;
import dao.Paci_DAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 276764
 */
public class CadastroPaciente extends javax.swing.JFrame {
    private Paciente paci = null;
    private Paci_DAO paciDAO = new Paci_DAO();
    
    int id = 0;

    /**
     * Creates new form CadastroPaciete
     */
    public CadastroPaciente() throws ClassNotFoundException, Exception{
        initComponents();
        
        id = paciDAO.IdIncrement().getId_paci();
        ID_PACI.setText(String.valueOf(id));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RG_PACI1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        posto = new javax.swing.JTextField();
        PostoSaude = new javax.swing.JLabel();
        NOME_PACI = new javax.swing.JTextField();
        END_PACI = new javax.swing.JTextField();
        TEL_PACI = new javax.swing.JTextField();
        EMAIL_PACI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CADASTRO_PAC = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel411 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rg_paci = new javax.swing.JTextField();
        ID_PACI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setText("CRM");

        posto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postoActionPerformed(evt);
            }
        });

        PostoSaude.setText("CNPJ DO POSTO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("RG");

        CADASTRO_PAC.setText("Cadastrar");
        CADASTRO_PAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTRO_PACActionPerformed(evt);
            }
        });

        jLabel9.setText("Nome");

        jLabel10.setText("Endereço");

        jLabel411.setText("Telefone");

        jLabel12.setText("E-mail");

        ID_PACI.setEnabled(false);

        jLabel7.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(CADASTRO_PAC)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(EMAIL_PACI, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel411)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ID_PACI)
                            .addComponent(NOME_PACI, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(END_PACI)
                            .addComponent(TEL_PACI)
                            .addComponent(rg_paci, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(ID_PACI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(rg_paci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOME_PACI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(END_PACI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel411)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TEL_PACI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EMAIL_PACI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CADASTRO_PAC)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CADASTRO_PACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTRO_PACActionPerformed
       if (validarFormulario()) {
        
            paci = new Paciente();
            paci.setNome_paci(NOME_PACI.getText().trim());
            paci.setRg_paci(rg_paci.getText().trim());
            paci.setEndereco_paci(END_PACI.getText().trim());
            paci.setTelefone_paci(Integer.parseInt(TEL_PACI.getText().trim()));
            paci.setEmail_paci(EMAIL_PACI.getText().trim());
           
            //parseDouble() converte o texto para double

          
                try {
                    paciDAO.inserir(paci);
                    //mensagem em caso de sucesso
                    
                    JOptionPane.showMessageDialog(this,"Dados Inseridos com sucesso");
                    
                    id = id + 1; 
                    //increment do id
                    
                     ID_PACI.setText(String.valueOf(id));
                    //retorna o valor do parametro como String
                        NOME_PACI.setText("");
                        rg_paci.setText("");
                        END_PACI.setText("");
                        TEL_PACI.setText("");
                        EMAIL_PACI.setText("");      
                     //limpando os campos após o cadastro
                  
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar paciente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    //mensagem informando qual erro ocorreu
                    return;
                }    
       }
    }//GEN-LAST:event_CADASTRO_PACActionPerformed

    private void postoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
   public boolean validarFormulario(){
      
        
        if(rg_paci.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Preencha o campo Rg.", "Alerta", JOptionPane.WARNING_MESSAGE);
             rg_paci.requestFocus();
             return false;
        
        }
        if(NOME_PACI.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha o campo Nome.", "Alerta", JOptionPane.WARNING_MESSAGE);
             NOME_PACI.requestFocus();
             return false;
        }
                if(END_PACI.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha o campo Endereço.", "Alerta", JOptionPane.WARNING_MESSAGE);
             END_PACI.requestFocus();
             return false;
        }
                
            if(TEL_PACI.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha o campo Telefone.", "Alerta", JOptionPane.WARNING_MESSAGE);
             TEL_PACI.requestFocus();
             return false;
        }
                            
            if(EMAIL_PACI.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha o campo E-mail.", "Alerta", JOptionPane.WARNING_MESSAGE);
             EMAIL_PACI.requestFocus();
             return false;
        }
       
    
            if (rg_paci.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "RG do paciente inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            rg_paci.requestFocus();
            return false;
        }
            
           if (NOME_PACI.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "Nome do paciente inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            NOME_PACI.requestFocus();
            return false;
        }
           
                       
           if (END_PACI.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "Endereço do paciente inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            END_PACI.requestFocus();
            return false;
        }
                                  
           if (TEL_PACI.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "Telefone do paciente inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            TEL_PACI.requestFocus();
            return false;
        }
                   if (EMAIL_PACI.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "E-mail do paciente inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            EMAIL_PACI.requestFocus();
            return false;
        }
    
         return true;
    }
    
 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CADASTRO_PAC;
    private javax.swing.JTextField EMAIL_PACI;
    private javax.swing.JTextField END_PACI;
    private javax.swing.JTextField ID_PACI;
    private javax.swing.JTextField NOME_PACI;
    private javax.swing.JLabel PostoSaude;
    private javax.swing.JTextField RG_PACI1;
    private javax.swing.JTextField TEL_PACI;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel411;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField posto;
    private javax.swing.JTextField rg_paci;
    // End of variables declaration//GEN-END:variables
}
